### PR TITLE
Fix strict mode from transaction block

### PR DESCRIPTION
**Pull request by bennichols**
We use strict mode for MobX and when using mobx-router, mutating the currentView within the transaction block is causing it to complain.

### CODE REVIEW

**Comment by kitze** [comment]
Tnx for the PR @bennichols. I have released a new version.

**Comment by elilambnz** [comment]
Thanks @kitze for the PR. When installing from npm, it doesn't look like the new changes are in the dist folder. Perhaps it didn't publish correctly?

**Comment by kitze** [comment]
Hmm, can you check 0.0.19?

**Comment by elilambnz** [comment]
Thanks @kitze, that's working fine now.

**Pull request merged**
